unbind-key -a -T root

unbind C-b
set-option -g prefix `
bind-key ` send-prefix

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g pane-border-lines "double"
setw -g mode-keys vi
set -s escape-time 0
set -g history-limit 2000

bind -n M-r source-file ~/dotfiles/tmux/.config/tmux/tmux.conf \; display "Config reloaded!"
bind -n M-s choose-tree -s

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-S-Left resize-pane -L 5
bind -n M-S-Right resize-pane -R 5
bind -n M-S-Up resize-pane -U 3
bind -n M-S-Down resize-pane -D 3

bind -n M-h split-window -v
bind -n M-v split-window -h

bind -n M-Enter new-window
bind -n M-c kill-pane
bind -n M-q kill-window
bind -n M-d detach
bind -n M-Q confirm-before -p "Kill entire session? (y/n)" kill-session

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy || xclip -in -selection clipboard"
bind -n M-/ copy-mode \; command-prompt -p "(search down)" "send -X search-forward '%%%'"
bind -n M-? copy-mode \; command-prompt -p "(search up)"   "send -X search-backward '%%%'"

# --- Manual minimalistic gruvbox theme ---
#set -g status-style "bg=#282828,fg=#ebdbb2" 
#set -g status-left-length 20
#set -g status-right-length 150
#set -g status-left ""
#set -g status-right "#[fg=#282828,bg=#fabd2f,bold] #S #[fg=#a89984,bg=#3c3836,nobold] %H:%M │ %d-%m #[fg=#282828,bg=#fabd2f,bold] #h "
#setw -g window-status-separator ""
#setw -g window-status-format "#[fg=#a89984,bg=#3c3836] #I | #W "
#setw -g window-status-current-format "#[fg=#282828,bg=#fe8019,bold] #I | #W "

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'z3z1ma/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# --- THEME CONFIGURATIONS
set -g @gruvbox_window_right_separator "█ "
set -g @gruvbox_window_number_position "right"
set -g @gruvbox_window_middle_separator " | "
set -g @gruvbox_window_default_fill "none"
set -g @gruvbox_window_current_fill "all"
set -g @gruvbox_status_modules_left ""
set -g @gruvbox_status_modules_right "session application battery date_time host"
set -g @gruvbox_status_left_separator "█"
set -g @gruvbox_status_right_separator "█"
set -g @gruvbox_date_time_text " %H:%M | %d-%m"

run '~/dotfiles/tmux/.config/tmux/plugins/tpm/tpm'
